"Filed out from Dolphin Smalltalk"!

Object subclass: #Articulo
	instanceVariableNames: 'codigo descripcion precio'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Articulo guid: (GUID fromString: '{a54ec2f8-b5b0-47cb-b159-1164e7dd6032}')!
Articulo comment: ''!
!Articulo categoriesForClass!Kernel-Objects! !
!Articulo methodsFor!

codigo
	^codigo!

codigo: anObject
	codigo := anObject!

hacerAlgo
2+2! !
!Articulo categoriesForMethods!
codigo!accessing!private! !
codigo:!accessing!private! !
hacerAlgo!public! !
!

